create table if not exists public.projects(
    id bigint generated by default as identity primary key,
    "group" text not null,
    title text not null,
    description text not null,
    image_url text,
    vote_count int not null default 0,
    created_at timestamptz not null default now()
);

create or replace function public.increment_votes(project_ids bigint[])
returns void
language plpgsql
security definer
as $$
begin
  update public.projects
  set vote_count = vote_count + 1
  where id = any(project_ids);
end;
$$;
