create table if not exists public.projects(
    id bigint generated by default as identity primary key,
    "group" text not null,
    title text not null,
    description text not null,
    image_url text,
    vote_count int not null default 0,
    created_at timestamptz not null default now()
);